TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += antonpaarldens3300.db
DATA += antonpaarldens3300.proto

#=======================================
include $(TOP)/configure/RULES
